spells/models.py
from sqlalchemy import Column, Boolean, SmallInteger, Integer, String
from spells.database import Model


class Spell(Model):
    __tablename__ = 'spells'
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    school = Column(String(25))
    subschool = Column(String(25))
    descriptor = Column(String(50))
    spell_level = Column(String(255))
    casting_time = Column(String(50))
    components = Column(String(255))
    costly_components = Column(Boolean)
    range = Column(String(255))
    area = Column(String(255))
    effect = Column(String(255))
    targets = Column(String(255))
    duration = Column(String(255))
    dismissible = Column(Boolean)
    shapeable = Column(Boolean)
    saving_throw = Column(String(255))
    spell_resistance = Column(String(50))
    description = Column(String(1024))
    description_formated = Column(String(1024))
    source = Column(String(50))
    full_text = Column(String(1024))
    verbal = Column(Boolean)
    somatic = Column(Boolean)
    material = Column(Boolean)
    focus = Column(Boolean)
    divine_focus = Column(Boolean)
    sor = Column(SmallInteger)
    wiz = Column(SmallInteger)
    cleric = Column(SmallInteger)
    druid = Column(SmallInteger)
    ranger = Column(SmallInteger)
    bard = Column(SmallInteger)
    paladin = Column(SmallInteger)
    alchemist = Column(SmallInteger)
    summoner = Column(SmallInteger)
    witch = Column(SmallInteger)
    inquisitor = Column(SmallInteger)
    oracle = Column(SmallInteger)
    antipaladin = Column(SmallInteger)
    magus = Column(SmallInteger)
    deity = Column(String(25))
    SLA_Level = Column(SmallInteger)
    domain = Column(String(50))
    short_description = Column(String(255))
    acid = Column(Boolean)
    air = Column(Boolean)
    chaotic = Column(Boolean)
    cold = Column(Boolean)
    curse = Column(Boolean)
    darkness = Column(Boolean)
    death = Column(Boolean)
    disease = Column(Boolean)
    earth = Column(Boolean)
    electricity = Column(Boolean)
    emotion = Column(Boolean)
    evil = Column(Boolean)
    fear = Column(Boolean)
    fire = Column(Boolean)
    force = Column(Boolean)
    good = Column(Boolean)
    language_dependent = Column(Boolean)
    lawful = Column(Boolean)
    light = Column(Boolean)
    mind_affecting = Column(Boolean)
    pain = Column(Boolean)
    poison = Column(Boolean)
    shadow = Column(Boolean)
    sonic = Column(Boolean)
    water = Column(Boolean)
    linktext = Column(String(50))
    material_costs = Column(Integer)
    bloodline = Column(String(50))
    patron = Column(String(50))

spells/__init__.py
"""
   Spells
   ~~~~~~

   :copyright: (c) 2013 by Adam Ness.
   :license: BSD, see LICENSE for more details
"""

from flask import Flask, render_template

app = Flask(__name__)
app.config.from_object('spells.websiteconfig')


@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404


@app.teardown_request
def remove_db_session(exception):
    db_session.remove()

from spells.views import main
from spells.views import api

app.register_blueprint(main.mod)
app.register_blueprint(api.mod, url_prefix='/api')

from spells.database import db_session

spells/views/api.py
from flask import Blueprint, json, jsonify, make_response, request
from spells.models import Spell

mod = Blueprint("api", __name__)


@mod.route('/autocomplete')
def autocomplete():
    term = request.values.get("term", "")
    spells = Spell.query.filter(Spell.name.like("%s%%" % term)).limit(5)
    names = map(lambda x: x[0], list(spells.values('name')))
    response = make_response(json.dumps(names))
    response.headers['Content-Type'] = 'application/json'
    return response


@mod.route('/spell')
def spell(name=""):
    name = request.values.get("name", "UNKNOWN")
    results = Spell.query.filter(Spell.name.like("%s%%" % name))
    spell = None
    error = None
    if results.count() == 0:
        response = make_response(json.dumps({'error': 'Couldn\'t find that spell'}), 404)
        response.headers['Content-Type'] = 'application/json'
        return response
    else:
        found_spell = results.limit(1)[0]
        spell = {
            'name': found_spell.name,
            'school': found_spell.school,
            'level': found_spell.spell_level,
            'casting_time': found_spell.casting_time,
            'components': found_spell.components,
            'range': found_spell.range,
            'target': found_spell.targets,
            'duration': found_spell.duration,
            'saving_throw': found_spell.saving_throw,
            'spell_resistance': found_spell.spell_resistance,
            'description': found_spell.description_formated
        }
    return jsonify(error=error, spell=spell)

spells/views/main.py
from flask import Blueprint, render_template

mod = Blueprint("main", __name__)


@mod.route('/')
def index():
    return render_template('main/index.html')


@mod.route('/listing')
def full_listing():
    return render_template('main/index.html')

spells/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}
    <title>{% block title %}Tome of Arcane Wisdom{% endblock %} | Pathfinder Spell Archive</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" media="screen">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-responsive.min.css') }}" media="screen">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" media="screen">
    <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">
    <link rel="apple-touch-icon-precomposed" href="{{ url_for('static', filename='touch-icon-57.png') }}">
    <link rel="apple-touch-icon-precomposed" size="72x72" href="{{ url_for('static', filename='touch-icon-72.png') }}">
    <link rel="apple-touch-icon-precomposed" size="114x114" href="{{ url_for('static', filename='touch-icon-114.png') }}">
    <link rel="apple-touch-icon-precomposed" size="144x144" href="{{ url_for('static', filename='touch-icon-144.png') }}">
    {% endblock head %}
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Tome of Arcane Wisdom</a>
          {% if session.logged_in %}
          <p class="navbar-text pull-right">
            Logged in as {{ session.username }}
          </p>
          {% else %}
          {% endif %}
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li {% if request.path == url_for('main.index') %}class="active"{% endif %}><a href="{{ url_for('main.index') }}">Home</a></li>
              <li {% if request.path == url_for('main.full_listing') %}class="active"{% endif %}><a href="{{ url_for('main.full_listing') }}">Full Listing</a><li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              {% block sidebar_nav %}
                <li class="nav-header">By Class</li>
                <li>Wizard/Sorcerer</li>
              {% endblock sidebar_nav %}
            </ul>
          </div>
        </div>
        <div class="span9">
        {% block body %}
          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details »</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details »</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details »</a></p>
            </div><!--/span-->
          </div><!--/row-->
          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details »</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details »</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details »</a></p>
            </div><!--/span-->
          </div><!--/row-->
        {% endblock body %}
        </div<!--/span9-->
      </div>
    </div>
    {% block javascript %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script type=text/javascript>
      $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% endblock javascript %}
  </body>
</html>

spells/templates/main/index.html
{% from "spells.html" import spell %}
{% extends "layout.html" %}

{% block head %}
{{ super() }}
  <style>
    #spell-area { display:none; }
  </style>
{% endblock head %}

{% block javascript %}
{{ super() }}
<script src="{{ url_for('static', filename="js/index.js") }}"></script>
{% endblock javascript %}

{% block body %}
<div class="hero-unit">
	<h1>Tome of Arcane Wisdom</h1>
	<form class="form-search">
		<input type="text" class="input-medium search-query" id="spell-searchbox">
		<button type="submit" class="btn" id="spell-searchbutton">Search</button>
	</form>
	<div id="notification">
	</div>
	<div id="spell-area">
	  {{ spell() }}
	</div>
</div>
{% endblock body %}

spells/templates/spells.html
{% macro spell( name='', school='', level='', casting_time='', components='', range='', target='', duration='', saving_throw='', spell_resistance='', description='' ) -%}
<div class="spell-name" id="name">{{name}}</div>
<div id="details">
<dl class="dl-horizontal">
  <dt>School</dt><dd id="school">{{school}}</dd>
  <dt>Level</dt><dd id="level">{{level}}</dd>
  <dt>Casting Time</dt><dd id="casting_time">{{casting_time}}</dd>
  <dt>Components</dt><dd id="components">{{components}}</dd>
  <dt>Range</dt><dd id="range">{{range}}</dd>
  <dt>Target</dt><dd id="target">{{target}}</dd>
  <dt>Duration</dt><dd id="duration">{{duration}}</dd>
  <dt>Saving Throw</dt><dd id="saving_throw">{{saving_throw}}</dd>
  <dt>Spell Resistance</dt><dd id="spell_resistance">{{spell_resistance}}</dd>
</dl>
</div>
<div id="description">{{description | safe}}
</div>
{%- endmacro %}